import * as XLSX from 'xlsx';

export function exportPurchaseListExcel({ items, bizName, bizRC }) {
  const now = new Date();
  const dateStr = now.toLocaleString('en-NG');
  const fileDateStr = now.toISOString().slice(0, 10);

  const wb = XLSX.utils.book_new();

  // Build rows: metadata header, blank, column headers, data, blank, summary
  const metaRows = [
    [bizName || 'Bevick Packaging Machineries'],
    [bizRC || 'RC: 967373'],
    ['Purchase Requirements'],
    [`Generated: ${dateStr}`],
    [],
    ['S/N', 'ITEM NAME', 'QTY'],
  ];

  const dataRows = items.map((item, idx) => [
    idx + 1,
    item.name,
    item.needed,
  ]);

  const totalUnits = items.reduce((s, i) => s + i.needed, 0);
  const summaryRows = [
    [],
    ['', 'TOTAL', totalUnits],
  ];

  const allRows = [...metaRows, ...dataRows, ...summaryRows];
  const ws = XLSX.utils.aoa_to_sheet(allRows);

  // Column widths
  ws['!cols'] = [
    { wch: 6 },   // S/N
    { wch: 40 },  // Item Name
    { wch: 10 },  // QTY
  ];

  XLSX.utils.book_append_sheet(wb, ws, 'Purchase List');
  XLSX.writeFile(wb, `Purchase-Requirements-${fileDateStr}.xlsx`);
}

// Builds the shared metadata + header + data + summary row layout used by
// both ledger export functions below.
function buildLedgerSheet({ rows, columns, bizName, bizRC, title, dateRangeLabel, generatedBy, summaryRows }) {
  const now = new Date();
  const dateStr = now.toLocaleString('en-NG');

  const metaRows = [
    [bizName || 'Bevick Packaging Machineries'],
    [bizRC || 'RC: 967373'],
    [title],
    [`Generated: ${dateStr}`],
    ...(generatedBy ? [[`Generated By: ${generatedBy}`]] : []),
    ...(dateRangeLabel ? [[`Period: ${dateRangeLabel}`]] : []),
    [],
    columns.map(c => c.label),
  ];

  const dataRows = rows.map(row => columns.map(c => {
    const raw = row[c.key];
    return c.format ? c.format(raw, row) : (raw ?? '');
  }));

  const summarySection = summaryRows?.length
    ? [[], ...summaryRows.map(s => ['', s.label, s.value])]
    : [];

  const allRows = [...metaRows, ...dataRows, ...summarySection];
  const ws = XLSX.utils.aoa_to_sheet(allRows);
  ws['!cols'] = columns.map(() => ({ wch: 18 }));
  return ws;
}

export function exportLedgerToExcel({ rows, columns, bizName, bizRC, title, dateRangeLabel, generatedBy, summaryRows, fileNamePrefix }) {
  const wb = XLSX.utils.book_new();
  const ws = buildLedgerSheet({ rows, columns, bizName, bizRC, title, dateRangeLabel, generatedBy, summaryRows });
  XLSX.utils.book_append_sheet(wb, ws, title.slice(0, 31));
  const fileDateStr = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `${fileNamePrefix || 'Ledger'}-${fileDateStr}.xlsx`);
}

export function exportLedgerToCSV({ rows, columns, fileNamePrefix }) {
  const header = columns.map(c => c.label);
  const body = rows.map(row => columns.map(c => {
    const raw = row[c.key];
    return c.format ? c.format(raw, row) : (raw ?? '');
  }));
  const ws = XLSX.utils.aoa_to_sheet([header, ...body]);
  const csv = XLSX.utils.sheet_to_csv(ws);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const fileDateStr = new Date().toISOString().slice(0, 10);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${fileNamePrefix || 'Ledger'}-${fileDateStr}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
